window.GUEST_NAME_MAP = {
  "1": "Ziad",
  "2": "Zoe",
  "3": "Rue",
  "4": "Fatma",
  "5": "Hana",
  "6": "Aregooo",
  "7": "Ahmed",
  "8": "Seif",
  "9": "Nourseen",
  "10": "Renoo",
  "11": "Reem",
  "12": "Nadoda",
  "13": "Nancy",
  "14": "Mariam",
  "15": "Mum",
  "16": "Dad",
  "17": "Hanouzy",
  "18": "Mariouma",
  "19": "Shetewi",
  "20": "Mennah",
  "21": "Rahma",
};